// ユーザー登録
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

// ログイン
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

// ユーザー情報取得
export const USER_SUCCESS = 'USER_SUCCESS'
export const USER_FAIL = 'USER_FAIL'

// リフレッシュトークン
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS'
export const REFRESH_FAIL = 'REFRESH_FAIL'

// 認証チェック
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS'
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL'

// ログアウト
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

// 読み込み中
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING'
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING'

// チェックアウト完了
export const CREATE_CHECKOUT_SUCCESS = 'CREATE_CHECKOUT_SUCCESS'
export const CREATE_CHECKOUT_FAIL = 'CREATE_CHECKOUT_FAIL'

// チェックアウト詳細
export const DETAIL_CHECKOUT_SUCCESS = 'DETAIL_CHECKOUT_SUCCESS'
export const DETAIL_CHECKOUT_FAIL = 'DETAIL_CHECKOUT_FAIL'
